exam/urls.py
from django.urls import path
from . import views
from exam.views.start_exam_view import StartExamView
from exam.views.text_based_view import TextBasedView
from exam.views.create_profile_view import CreateProfileView
from exam.views.mcq_based_view import MCQBasedView
from exam.views.approve_exam import approve_exam
from exam.views.cancel_exam import cancel_exam
from exam.views.check_exam_view import check_exam_view
from exam.views.create_exam import create_exam
from exam.views.delete_question import delete_question
from exam.views.exam_list import exam_list
from exam.views.exam_submission import exam_submission
from exam.views.question_view import question_view
from exam.views.signup import signup
from exam.views.student_view import student_view
from exam.views.user_login import user_login
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500


urlpatterns = [
    path("", views.views.home, name="home"),
    path("logout/", views.views.user_logout, name="logout"),
    path("question-view/take", views.views.questions_take, name="questions-take"),
    path("signup/", signup, name="signup"),
    path("login/", user_login, name="login"),
    path("exam-submission/", exam_submission, name="exam_submission"),
    path("question-view/<str:name>/", question_view, name="question"),
    path("question-view/<int:pk>", delete_question, name="question_delete"),
    path("student-dashboard/", student_view, name="student_dashboard"),
    path("student/<int:exam_id>/check/", check_exam_view, name="check_exam"),
    path("accounts/login/", user_login, name="login"),
    path("exams/", exam_list, name="exam_list"),
    path("exams/create/", create_exam, name="create_exam"),
    path("exams/mcq-based", MCQBasedView.as_view(), name="mcq-based"),
    path("exams/text-based", TextBasedView.as_view(), name="text-based"),
    path("exams/<int:exam_id>/cancel/", cancel_exam, name="cancel_exam"),
    path("exams/<int:exam_id>/approve/", approve_exam, name="approve_exam"),
    path("create_profile/", CreateProfileView.as_view(), name="create_profile"),
    path("start-exam/<int:exam_id>/", StartExamView.as_view(), name="start_exam"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from django.conf.urls.static import static
from project import settings
from django.views.static import serve
from django.conf.urls import handler404, handler500


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("exam.urls")),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = "exam.views.views.error_404"
handler500 = "exam.views.views.error_500"

exam/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from cloudinary.models import CloudinaryField
from django.core.validators import MinValueValidator


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    user_type = models.CharField(
        choices=[("teacher", "Teacher"), ("student", "Student")],
        max_length=10,
    )
    profile_picture = CloudinaryField("image")

    def __str__(self):
        return self.user.first_name


class Subject(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Exam(models.Model):
    teacher = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name="exams_created", null=True
    )
    subject = models.ForeignKey(
        Subject, on_delete=models.SET_NULL, related_name="exams", null=True
    )
    start_time = models.DateTimeField(default=datetime.now().strftime("%Y-%m-%d %H:%M"))
    end_time = models.DateTimeField(default=datetime.now().strftime("%Y-%m-%d %H:%M"))
    is_approved = models.BooleanField(default=False)
    is_requested = models.BooleanField(default=False)
    is_visible = models.BooleanField(default=False)

    def clean(self):
        if self.start_time >= self.end_time:
            raise ValidationError("End time must be greater than start time.")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.subject.name


class Question(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.DO_NOTHING, null=True)
    score = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    question_text = models.TextField()
    question_type = models.CharField(
        choices=[("multiple_choice", "Multiple Choice"), ("text_based", "Text Based")],
        max_length=100,
    )

    def __str__(self):
        return self.question_text


class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    option1 = models.CharField(max_length=25, null=True)
    option2 = models.CharField(max_length=25, null=True)
    option3 = models.CharField(max_length=25, null=True)
    option4 = models.CharField(max_length=25, null=True)
    answer = models.IntegerField(
        choices=[(1, "Option 1"), (2, "Option 2"), (3, "Option 3"), (4, "Option 4")],
        null=True,
    )
    text_answer = models.CharField(max_length=25, null=True)

    def __str__(self):
        return self.question.question_text


class Attempt(models.Model):
    student = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name="attempts")
    score = models.PositiveIntegerField(default=0)
    is_attempted = models.BooleanField(default=False)

    def __str__(self):
        return self.exam.subject.name


class AttemptQuestion(models.Model):
    student = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="attempts", null=True
    )
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    selected_option = models.CharField(max_length=20, null=True)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.question.question_text


class ApprovalRequest(models.Model):
    teacher = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="approval_requests"
    )
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.exam.subject.name


class TempSessionScore(models.Model):
    score = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.score}"

exam/views/check_exam_view.py
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.contrib.auth.decorators import (
    login_required,
    user_passes_test,
)
from django.shortcuts import (
    render,
    get_object_or_404,
)

from exam.views.views import is_student
from exam.models import (
    Attempt,
    AttemptQuestion,
)


@login_required(login_url="login")
@user_passes_test(is_student)
def check_exam_view(request, exam_id):
    user = request.user

    try:
        attempt_score = get_object_or_404(Attempt, student=user, exam_id=exam_id)
    except Http404:
        raise PermissionDenied("You are not authorized to view this exam.")

    attempted_questions = AttemptQuestion.objects.filter(
        student=user, question__exam_id=exam_id
    )

    return render(
        request,
        "check-exam-view.html",
        {
            "exam_id": exam_id,
            "attempt_score": attempt_score,
            "attempted_questions": attempted_questions,
        },
    )

exam/views/create_exam.py
from django.contrib import messages
from django.contrib.auth.decorators import (
    login_required,
    user_passes_test,
)
from django.shortcuts import (
    render,
    redirect,
)

from exam.views.views import is_teacher
from exam.forms import (
    ExamForm,
)
from exam.models import (
    Exam,
)


@login_required(login_url="login")
@user_passes_test(is_teacher)
def create_exam(request):
    try:
        if request.method == "POST":
            exam_form = ExamForm(request.POST)

            if exam_form.is_valid():
                exam = exam_form.save(commit=False)
                exam.teacher = request.user
                existing_exam = Exam.objects.filter(subject=exam.subject).first()

                if existing_exam:
                    messages.warning(request, "Exam already exists.")
                else:
                    exam.save()
                    messages.success(
                        request, "Exam Created! Now add questions to the exam."
                    )
                    return redirect("questions-take")
        else:
            exam_form = ExamForm()

        return render(request, "create-exam.html", {"exam_form": exam_form})
    except Exception as e:
        context = {"error": str(e)}
        return render(request, "admin/error.html", context)

exam/views/create_profile_view.py
from django.views import View
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import (
    render,
    redirect,
)
from exam.forms import (
    ProfileForm,
)
from exam.models import (
    Profile,
)


class CreateProfileView(View):
    def get(self, request):
        try:
            existing_profile = Profile.objects.get(user=request.user)
        except ObjectDoesNotExist:
            existing_profile = None
        form = ProfileForm(instance=existing_profile)
        return render(request, "create_profile.html", {"form": form})

    def post(self, request):
        try:
            existing_profile = Profile.objects.get(user=request.user)
        except ObjectDoesNotExist:
            existing_profile = None
        form = ProfileForm(request.POST, request.FILES, instance=existing_profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, "Profile created successfully!")
            return redirect("home")
        else:
            return render(request, "create_profile.html", {"form": form})

exam/views/exam_submission.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.db.models import Count
from django.contrib.auth.decorators import (
    login_required,
    user_passes_test,
)
from django.shortcuts import (
    render,
    redirect,
)

from exam.views.views import is_teacher
from exam.models import (
    Question,
    Subject,
    User,
    Exam,
    Attempt,
)


@login_required(login_url="login")
@user_passes_test(is_teacher)
def exam_submission(request):
    try:
        subjects = Subject.objects.all()
        subject_count = len(subjects)
        student_count = User.objects.count()
        question_count = Question.objects.count()
        exams = Exam.objects.annotate(question_count=Count("question"))
        exam = Exam.objects.filter(is_approved=True)
        attempts = Attempt.objects.filter(exam__in=exam)
        questions = Question.objects.all()

        if "request-btn" in request.POST:
            if Exam.objects.filter(is_requested=True).exists():
                messages.warning(request, "Exam request already exists!")
                return redirect("exam_submission")
            else:
                exam_id = request.POST.get("exam_id")
                exam = Exam.objects.get(id=exam_id)
                exam.is_requested = True
                exam.save()
                messages.success(request, "Exam requested successfully!")
                return redirect("exam_submission")
        return render(
            request,
            "exam-submission.html",
            {
                "attempts": attempts,
                "subjects": subjects,
                "subject_count": subject_count,
                "student_count": student_count,
                "question_count": question_count,
                "exams": exams,
                "questions": questions,
            },
        )
    except Exception as e:
        context = {"error": str(e)}
        return render(request, "admin/error.html", context)

exam/views/mcq_based_view.py
from django.views import View
from django.contrib import messages
from django.http import Http404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import (
    login_required,
    user_passes_test,
)
from django.shortcuts import (
    render,
    redirect,
)

from exam.views.views import is_teacher
from exam.forms import (
    QuestionForm,
    OptionForm,
)
from exam.models import (
    Exam,
)


@method_decorator(login_required(login_url="login"), name="dispatch")
@method_decorator(user_passes_test(is_teacher), name="dispatch")
class MCQBasedView(View):
    template_name = "mcq-based.html"
    question_form_class = QuestionForm
    option_form_class = OptionForm

    def get(self, request, *args, **kwargs):
        question_form = self.question_form_class()
        option_form = self.option_form_class()
        return render(
            request,
            self.template_name,
            {
                "question_form": question_form,
                "option_form": option_form,
            },
        )

    def post(self, request, *args, **kwargs):
        try:
            question_form = self.question_form_class(request.POST)
            option_form = self.option_form_class(request.POST)
            if question_form.is_valid() and option_form.is_valid():
                question = question_form.save(commit=False)
                question.question_type = "multiple_choice"
                question.subject = question.exam.subject
                question.save()
                option = option_form.save(commit=False)
                option.question = question
                option.save()
                messages.success(request, "Question added")
                return redirect("mcq-based")
            if "request-btn" in request.POST:
                if Exam.objects.filter(is_requested=True).exists():
                    messages.warning(request, "Exam request already exists.")
                else:
                    exam_id = request.POST.get("exam_id")
                    exam = Exam.objects.get(id=exam_id)
                    exam.is_requested = True
                    exam.save()
        except Exam.DoesNotExist:
            raise Http404("Exam does not exist.")
        except Exception as e:
            print(e)
            messages.error(request, "An error occurred. Please try again later.")
            return redirect("home")
        return render(
            request,
            "mcq-based.html",
            {
                "question_form": question_form,
                "option_form": option_form,
            },
        )

exam/views/question_view.py
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import (
    login_required,
    user_passes_test,
)
from django.shortcuts import (
    render,
)

from exam.views.views import is_teacher
from exam.models import (
    Question,
    Subject,
    User,
)


@login_required(login_url="login")
@user_passes_test(is_teacher)
def question_view(request, name):
    try:
        subject_count = Subject.objects.count()
        student_count = User.objects.count()
        question_count = Question.objects.count()
        my_param = (
            Question.objects.filter(Q(exam__subject__name__icontains=name))
            .select_related("exam__subject")
            .values(
                "id",
                "exam__subject__name",
                "question_text",
                "score",
            )
        )

        return render(
            request,
            "question-view.html",
            {
                "my_param": my_param,
                "subject_count": subject_count,
                "student_count": student_count,
                "question_count": question_count,
            },
        )
    except Exception as e:
        context = {"error": str(e)}
        return render(request, "admin/error.html", context)

exam/views/signup.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import (
    render,
    redirect,
)
from exam.forms import (
    SignUpForm,
)


def signup(request):
    form = SignUpForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            form.save()
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "Form Submitted Success")
            return redirect("create_profile")
        else:
            error_message = form.errors.as_data().popitem()[1][0].message
            messages.error(request, error_message)
    context = {"form": form}
    return render(request, "signup.html", context)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Examination Registeration</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Examify</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if user.groups.all %}
          {% for group in user.groups.all %}
              {% if group.name == 'Teacher' %}
                  <li class="nav-item">
                    <a class="nav-link" href="{%url 'exam_submission' %}">Teacher</a>
                  </li>
              {% endif %}
              {% if group.name == 'Student' %}
                  <li class="nav-item">
                    <a class="nav-link" href="{%url 'student_dashboard' %}">Student</a>
                  </li>
              {% endif %}
          {% endfor %}
      {% endif %}
      {% if perms.auth.view_user %}
      <li class="nav-item">
        <a class="nav-link" href="{%url 'exam_list' %}">Admin</a>
      </li>
      {% endif %}
    </ul>
    {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link"Admin>Welcome, {{ user.username }}!</a>
    </li>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="{% url 'logout' %}">Logout</a></button>
    {% else %}
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="{% url 'login' %}">Login</a></button>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="{% url 'signup' %}">Signup</a></button>
    {% endif %}
  </div>
</nav>

<body>
      <div class="d-flex justify-content-center">
      {% if messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %} {% endif %}
    </div>
  {% block content%}
  {% endblock content%}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
    <script>
    document.addEventListener("DOMContentLoaded", function () {
      // Auto-dismiss messages after 5 seconds (5000 milliseconds)
      var alerts = document.querySelectorAll(".alert");
      setTimeout(function () {
        for (var i = 0; i < alerts.length; i++) {
          alerts[i].remove();
        }
      }, 5000);
    });
  </script>
</body>

</html>

templates/basic_exam.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="col-md-10 offset-md-1 mt-5">
		<div class="jumbotron">
			<h1>Take Exam: {{ exam.subject }}</h1>
            <form method="post">
                {% csrf_token %}
                {% for question in questions %}
                <div>
                    <label>{{ question.question_text }}</label>
                    {% for option in question.option_set.all %}
                    <div>
                        <input type="{{ question.question_type }}" name="question-{{ question.id }}" value="{{ option.id }}" id="option{{ option.id }}">
                        <label for="option{{ option.id }}">
                            {{ option.option1 }}
                            {% if option.option2 %}, {{ option.option2 }}
                            {% endif%}
                            {% if option.option3 %}, {{ option.option3 }}
                            {% endif %}
                            {% if option.option4 %}, {{ option.option4}}
                            {% endif %}
                        </label>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>


<div class="container">
	<div class="col-md-10 offset-md-1 mt-5">
		<div class="jumbotron">
			<h1>Take Exam: {{ exam.subject }}</h1>
            <form method="post">
                {% csrf_token %}
                {% for question in questions %}
                <div>
                    <label>{{ question.question_text }}</label>
                    {% for option in question.option_set.all %}
                    <div>
                        <!-- <input type="{{ question.question_type }}" name="question-{{ question.id }}" value="{{ option.id }}" id="option{{ option.id }}"> -->
                        <label for="option{{ option.id }}">
                            <div class="form-check mx-4">
                                <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{ option.option1 }}"
                                    value="1">
                                <label class="form-check-label" for="option1">
                                    {{ option.option1}}
                                </label>
                            </div>
                            <div class="form-check mx-4">
                                <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{ option.option2  }}"
                                    value="1">
                                <label class="form-check-label" for="option2">
                                    {{ option.option2}}
                                </label>
                            </div>
                            <div class="form-check mx-4">
                                <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{ option.option3 }}"
                                    value="1">
                                <label class="form-check-label" for="option3">
                                    {{ option.option3}}
                                </label>
                            </div>
                            <div class="form-check mx-4">
                                <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{ option.option4 }}"
                                    value="1">
                                <label class="form-check-label" for="option4">
                                    {{ option.option4}}
                                </label>
                            </div>
                        </label>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/check-exam-view.html
{% extends 'base.html' %} 

{% block content%}

<div class="container">
  <div class="col-md-10 offset-md-1 mt-5">
    <div class="jumbotron">
      <h1 class="display-4">Check Exam Marks</h1>
      <hr class="my-4">
      <table class="table table-hover table-bordered" id="dev-table">
            <thead>
              <tr>
                <th>#</th>
                <th>Question</th>
                <th>Score</th>
                <th>Correct / Incorrect</th>
              </tr>
            </thead>
            {% for t in attempted_questions %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td>{{t}}</td>
              <td>{{ t.question.score }}</td>
              {% if t.is_correct %}
                <td>Correct</td>
              {% else %}
                <td>Incorrect</td>
              {% endif %}
            </tr>
            {% endfor %}
          </table>
          <h1 class="text-right">Total Marks: {{attempt_score.score}}</h1>
    </div>  
  </div>
</div>

{% endblock content%}

templates/create-exam.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="col-md-10 offset-md-1 mt-5">
		<div class="jumbotron">
			<h1 class="display-4">Create Exam</h1>
            <hr class="my-4">
            <form method="POST">
                {% csrf_token %}
                {{ exam_form.as_p }}
                <button class="btn btn-success btn-xs" type="submit">Create Exam</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/start-exam.html
{% extends 'base.html' %}

{% block content%}

<div class="container">
    <div class="col-md-10 offset-md-1 mt-5">
        <div class="jumbotron my-4">
            {% for obj in page_obj %}
            <h2 style="text-align: center;">Exam: {{exam_id}}</h2>
            {% endfor %}
            {% for question in page_obj %}
            {% if question.question_type == "multiple_choice" %}
                <form class="form" method="POST" action="?page={{ page_obj.number }}">
                    {% csrf_token %}
                    <div>
                        <label>{{ question.question_text }}</label>
                            <input type="hidden" name="question_id" value="{{ question.id }}" id="option{{ question.id }}">
                        {% for option in question.option_set.all %}
                        <div>
                            <input type="hidden" name="option_id" value="{{ option.id }}" id="option{{ option.id }}">
                            <label for="option{{ option.id }}">
                                <div class="form-check mx-4">
                                    <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{ option.option1 }}"
                                        value="1" required>
                                    <label class="form-check-label" for="option1">
                                        {{ option.option1}}
                                    </label>
                                </div>
                                <div class="form-check mx-4">
                                    <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{ option.option2  }}"
                                        value="2" required>
                                    <label class="form-check-label" for="option2">
                                        {{ option.option2}}
                                    </label>
                                </div>
                                <div class="form-check mx-4">
                                    <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{ option.option3 }}"
                                        value="3" required>
                                    <label class="form-check-label" for="option3">
                                        {{ option.option3}}
                                    </label>
                                </div>
                                <div class="form-check mx-4">
                                    <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{ option.option4 }}"
                                        value="4" required>
                                    <label class="form-check-label" for="option4">
                                        {{ option.option4}}
                                    </label>
                                </div>
                            </label>
                        </div>
                        {% endfor %}
                    </div>
                    <br>
                    <div class="pagination">
                        <span class="step-links">
                            <span class="current-page">
                                Question {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                        </span>
                    </div>
                    <br>
                    {% if page_obj.number == page_obj.paginator.num_pages %}
                    <input name="attempt_completed" type="hidden" value="{{True}}">
                    {% endif %}
                    <button name="exam_button" class="btn btn-success btn-lg" type="submit" value="Submit">Submit &rsaquo;</button>
                </form>
            {% else %}
                <form class="form" method="POST" action="?page={{ page_obj.number }}">
                    {% csrf_token %}
                    <input type="hidden" name="question_id" value="{{ question.id }}">
                    <label>{{ question.question_text }}</label>
                    <br>
                    <textarea name="answer"></textarea>
                    <br>
                    <br>
                    {% if page_obj.number == page_obj.paginator.num_pages %}
                    <input name="attempt_completed" type="hidden" value="{{True}}">
                    {% endif %}
                    <button name="exam_button" class="btn btn-success btn-lg" type="submit" value="Submit">Submit</button>
                </form>
            {% endif %}
            {% endfor %}

        </div>
    </div>
</div>
{% endblock content%}